server:
    port: 9100
spring:
    datasource:
        driverClassName: org.h2.Driver
        password: ''
        url: jdbc:h2:mem:testdb
        username: sa
    h2:
        console:
            enabled: true
    kafka:
        consumer:
            bootstrap-servers: kafkaserver:9092
            group-id: customerservice
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        producer:
            bootstrap-servers: kafkaserver:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
management:
  security:
    enabled: false
