version: '3.4'

services:
  configserver:
    image: configserver
    ports:
      - "8000:8000"
  gateway:
    image: gateway
    ports:
      - "9000:9000"
    depends_on:
      - configserver

  customerservice:
    image: customerservice
    ports:
      - "9100:9100"
    depends_on:
      - configserver

  orderservice:
    image: orderservice
    ports:
      - "9200:9200"
    depends_on:
      - configserver