server:
    port: 9000
eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
spring:
  cloud:
    gateway:
      routes:
      - id: customerroute
        uri: lb://customerservice
        predicates:
        - Path=/order/**
      - id: orderroute
        uri: lb://orderservice
        predicates:
        - Path=/customer/**
