server:
    port: 9000
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka, http://192.168.99.100:8761/eureka
spring:
  cloud:
    gateway:
      routes:
      - id: customerroute
        uri: lb://customerservice
        predicates:
        - Path=/customer/**
      - id: orderroute
        uri: lb://orderservice
        predicates:
        - Path=/order/**
