version: '3.4'

services:
  configserver:
    image: configserver
    ports:
      - "8000:8000"
  discoveryserver:
    image: discoveryserver
    ports:
      - "8761:8761"
    depends_on:
      - configserver    
  gateway:
    image: gateway
    ports:
      - "9300:9300"
    depends_on:
      - configserver
      - discoveryserver
  customerservice:
    image: customerservice
    ports:
      - "9100:9100"
    depends_on:
      - configserver
      - discoveryserver
  orderservice:
    image: orderservice
    ports:
      - "9200:9200"
    depends_on:
      - configserver
      - discoveryserver
  kafkaserver:
    image: "spotify/kafka:latest"
    container_name: kafka
    hostname: kafkaserver
    networks:
      - kafkanet
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      ADVERTISED_HOST: kafkaserver
      ADVERTISED_PORT: 9092
  kafka_manager:
    image: "mzagar/kafka-manager-docker:1.3.3.4"
    container_name: kafkamanager
    networks:
      - kafkanet
    ports:
      - 9000:9000
    links:
      - kafkaserver
    environment:
      ZK_HOSTS: "kafkaserver:2181"

networks:
  kafkanet:
    driver: bridge
      